// bling.js from https://gist.github.com/paulirish/12fb951a8b893a454b32

window.$ = document.querySelectorAll.bind(document);

Node.prototype.on = window.on = function (name, fn) {
  this.addEventListener(name, fn);
}

NodeList.prototype.__proto__ = Array.prototype;

(function(){

const codeContainer = () => {
  pre = document.createElement('pre');
  pre.innerHTML = `<code data-trim data-es5></code>`
  pre.classList.add('es5_code_container');
  return pre;
}

const addCodeMainContainer = sectionElem => {
  const div = document.createElement('div');
  div.classList.add('code_main_container');
  sectionElem.appendChild(div);
  return div
}

const addToMainContainer = (main, elem) => {
  main.appendChild(elem);
}

const codeHeader = name => {
  const newCodeHeader = document.createElement('h3');
  newCodeHeader.innerHTML = name;
  newCodeHeader.classList.add('code_header');
  return newCodeHeader;
}

const es6ToEs5 = es6code => {
  const compiler = new traceur.Compiler();
  const es5code = compiler.compile(es6code);
  const codeStartMarker = 'var __moduleName = "'
  const codeEndMarker = 'return {};'
  const codeStartMarkerPos = es5code.indexOf(codeStartMarker) + codeStartMarker.length + 18;
  const codeEndMarkerPos = es5code.indexOf(codeEndMarker) - 2;

  const es5CodeUnwrapped = es5code.substring(codeStartMarkerPos, codeEndMarkerPos);
  return es5CodeUnwrapped;
}

const updateEs5CodeFor = (section, code) => {
  section.querySelector('code[data-es5]').innerText = code;
}

const divWithClass = className => {
  const div = document.createElement('div');
  div.classList.add(className);
  return div;
}

$('code[data-es6]').forEach(es6CodeContainer => {
    const section = es6CodeContainer.parentNode.parentNode;
    const main = addCodeMainContainer(section);
    const es5MainContainer = divWithClass('es5_main')
    const es6MainContainer = divWithClass('es6_main')
    es6MainContainer.appendChild(codeHeader('ES6'));
    es6MainContainer.appendChild(es6CodeContainer.parentNode);
    es5MainContainer.appendChild(codeHeader('ES5'));
    es5MainContainer.appendChild(codeContainer());
    main.appendChild(es5MainContainer);
    main.appendChild(es6MainContainer);
    updateEs5CodeFor(section, es6ToEs5(es6CodeContainer.innerText));
    es6CodeContainer.addEventListener('keyup', e => updateEs5CodeFor(section, es6ToEs5(es6CodeContainer.innerText)));
});


/*
function lsToJsFrom(elem) {
  try {
    return "\n" + $(elem).text().toString(); // LiveScript.compile($(elem).text(), {bare: true});
  } catch(e) {
    showError(elem, 'Compile', e);
  }
}

function removeCodeResults(elem) {
  $(elem).closest('section').find('.code_result').remove();
}

function appendResultContainers(elem) {
  $(elem).closest('section')
      .append(jsCompileResultDiv())
      .append(jsRunLogDiv());
}

function evalJsCode(elem, jsCode) {
  var orig_log = console.log;

  l = console.log = function() {
    var args = Array.prototype.slice.call(arguments);
    var $section = $(elem).closest('section');
    var $runLogCodeElem = $(elem).closest('section').find('.run_log code');
    $section.find('.run_log').show();
    args.forEach(function(arg) {$runLogCodeElem.append(arg);});
    $runLogCodeElem.append("\n");
  };

  d = function() {
    var args = Array.prototype.slice.call(arguments);
    l(args.map(function(arg) {return JSON.stringify(arg)}));
  }

  try {
    evalResult = eval(jsCode);
    showResult(elem, JSON.stringify(evalResult));
  } catch(e) {
    showError(elem, 'Runtime', e);
  }

  console.log = orig_log;
}

function showJsCode(elem, code) {
  $(elem).closest('section').find('.js_result code').html(code.substr("// Generated by LiveScript 1.2.0\n".length));
}

function jsCompileResultDiv(jsCode) {
  return '<div class="code_result js_result">' +
      '<h3>JavaScript</h3><pre><code data-trim ></code></pre>' +
    '</div>';
}

function jsRunLogDiv() {
  return '<div class="code_result run_log">' +
      '<h3>Run Log</h3><pre><code data-trim></code></pre>' +
    '</div>';
}

function showResult(elem, result)  {
  if (result === "" || result === undefined) return;
  var jsRunResultDiv =
    '<div class="code_result run_result"><h3>Result</h3>' +
      '<pre><code data-trim>' + result + '</code></pre>' +
    '</div>';
  $(elem).closest('section').append($(jsRunResultDiv));
}

function showError(elem, errorType, errorMessage) {
  var $section = $(elem).closest('section');
  $section.find('.run_log').show();
  $(elem).closest('section').find('.run_log h3').html(errorType + ' Error').css({color: 'red'});
  $(elem).closest('section').find('.run_log code').append(errorMessage).css({color: 'red'});
}

*/
})();
